[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/RigExec/L_RigExec.L_RigExec
GameDefaultMap=/Game/RigExec/L_RigExec.L_RigExec

[/Script/Engine.Engine]
; Hides the viewport warning the engine draws while stats are collected.
bDisableAILogging=True

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=920624D14834E20264C8D9A12F6FF9C6
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

